<h3>Добавление новости</h3>

<form method="post" action="/add">
    <div class="form-field">
        <div class="form-label">
            <label>Название</label>
        </div>
        <div class="form-data">
            <input class="form-input" type="text" name="title" value="">
        </div>
    </div>

    <div class="form-field">
        <div class="form-label">
            <label>Текст</label>
        </div>
        <div class="form-data">
            <textarea class="form-text" name="text"></textarea>
        </div>
    </div>

    <input type="submit">
</form>