<h3>Новости</h3>

<?if($this->news):?>
<div class="news">
<?foreach($this->news as $newsItem):?>
    <div class="news-item">
        <div class="news-item-title"><h4><?=$newsItem->title?></h4></div>
        <div class="news-item-text"><?=nl2br($newsItem->text)?></div>
        <div class="news-item-date-created"><?=$newsItem->date_created?></div>

        <div class="news-item-buttons">
            <a class="btn" href="/delete?id=<?=$newsItem->id?>">Удалить</a>
            <a class="btn" href="/edit?id=<?=$newsItem->id?>">Изменить</a>
        </div>
    </div>
<?endforeach;?>
</div>
<?endif;?>

<div class="news-add-button">
<a class="btn" href="/add">Добавить новость</a>
</div>