<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
    <link rel="stylesheet" type="text/css" media="all" href="/styles.css"/>
    <title><?=$this->pageTitle?></title>
</head>
<body>
    <div id="main-container">
        <div id="main-header">

        </div>
        <div id="main-content">
            <?=$this->_tplContent?>
        </div>
        <div id="main-footer">
            <a href="/">Новостная лента</a>
        </div>
    </div>
</body>
</html>

